DROP TABLE IF EXISTS INQUIRIES ;
DROP TABLE IF EXISTS QUESTINS ;

CREATE TABLE INQUIRIES
  (
     id        INT PRIMARY KEY AUTO_INCREMENT,
     subject VARCHAR(100),
     body  VARCHAR(500)
  ) CHARACTER SET utf8 COLLATE utf8_unicode_ci;
  
CREATE TABLE QUESTIONS
  (
    id  INT PRIMARY KEY AUTO_INCREMENT,
    body  VARCHAR(500),
	single BOOLEAN ,
	inquiry_id INT NOT NULL,
	CONSTRAINT FK_QUESTION_1 FOREIGN KEY (inquiry_id)
                  REFERENCES inquiries (id) ON DELETE CASCADE
  ) CHARACTER SET utf8 COLLATE utf8_unicode_ci;
  